pipeline {

    agent any
    tools {
        maven "MAVEN3"
        jdk "OpenJDK8"
    }

    stages {
        stage('Fetch code'){
            steps {
                git branch: 'vp-rem', url: 'https://github.com/devopshydclub/vprofile-project.git'
            }
        }

        stage ('Build') {
            steps {
                sh 'mvn install'
            }

            post {
                success {
                    echo 'Now Archiving it...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }

        stage ('Test') {
            steps{
                sh 'mvn test'
            }
        }
    }

}